// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: target.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X1 int32 `protobuf:"varint,1,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1 int32 `protobuf:"varint,2,opt,name=y1,proto3" json:"y1,omitempty"`
	X2 int32 `protobuf:"varint,3,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2 int32 `protobuf:"varint,4,opt,name=y2,proto3" json:"y2,omitempty"`
}

func (x *Rect) Reset() {
	*x = Rect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_target_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rect) ProtoMessage() {}

func (x *Rect) ProtoReflect() protoreflect.Message {
	mi := &file_target_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rect.ProtoReflect.Descriptor instead.
func (*Rect) Descriptor() ([]byte, []int) {
	return file_target_proto_rawDescGZIP(), []int{0}
}

func (x *Rect) GetX1() int32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *Rect) GetY1() int32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *Rect) GetX2() int32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *Rect) GetY2() int32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

type Circle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R  int32 `protobuf:"varint,1,opt,name=r,proto3" json:"r,omitempty"`
	X1 int32 `protobuf:"varint,2,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1 int32 `protobuf:"varint,3,opt,name=y1,proto3" json:"y1,omitempty"`
}

func (x *Circle) Reset() {
	*x = Circle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_target_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Circle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Circle) ProtoMessage() {}

func (x *Circle) ProtoReflect() protoreflect.Message {
	mi := &file_target_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Circle.ProtoReflect.Descriptor instead.
func (*Circle) Descriptor() ([]byte, []int) {
	return file_target_proto_rawDescGZIP(), []int{1}
}

func (x *Circle) GetR() int32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *Circle) GetX1() int32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *Circle) GetY1() int32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

var File_target_proto protoreflect.FileDescriptor

var file_target_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x04, 0x52, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x78, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x78, 0x31, 0x12, 0x0e, 0x0a,
	0x02, 0x79, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x79, 0x31, 0x12, 0x0e, 0x0a,
	0x02, 0x78, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x78, 0x32, 0x12, 0x0e, 0x0a,
	0x02, 0x79, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x79, 0x32, 0x22, 0x36, 0x0a,
	0x06, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x78, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x78, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x79, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x79, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_target_proto_rawDescOnce sync.Once
	file_target_proto_rawDescData = file_target_proto_rawDesc
)

func file_target_proto_rawDescGZIP() []byte {
	file_target_proto_rawDescOnce.Do(func() {
		file_target_proto_rawDescData = protoimpl.X.CompressGZIP(file_target_proto_rawDescData)
	})
	return file_target_proto_rawDescData
}

var file_target_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_target_proto_goTypes = []interface{}{
	(*Rect)(nil),   // 0: TargetDetection.proto.Rect
	(*Circle)(nil), // 1: TargetDetection.proto.Circle
}
var file_target_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_target_proto_init() }
func file_target_proto_init() {
	if File_target_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_target_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_target_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Circle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_target_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_target_proto_goTypes,
		DependencyIndexes: file_target_proto_depIdxs,
		MessageInfos:      file_target_proto_msgTypes,
	}.Build()
	File_target_proto = out.File
	file_target_proto_rawDesc = nil
	file_target_proto_goTypes = nil
	file_target_proto_depIdxs = nil
}
